[package]
name = "avoevents-queries"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
spin-sdk = { workspace = true }
